services:
  app:
    image: analytics_api:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    # environment:
    #   - PORT=8000
    #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env.compose
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code:rw
    depends_on:
      db_service:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  # postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-pw
      - POSTGRES_DB=timescaledb
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U time-user -d timescaledb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  timescaledb_data:

